apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-picture-frontend
  labels:
    app: movie-picture-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-picture-frontend
  template:
    metadata:
      labels:
        app: movie-picture-frontend
    spec:
      containers:
        - name: movie-picture-frontend
          image: movie-picture-frontend
          ports:
            - containerPort: 3000
