apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-picture-backend
  labels:
    app: movie-picture-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-picture-backend
  template:
    metadata:
      labels:
        app: movie-picture-backend
    spec:
      containers:
        - name: movie-picture-backend
          image: movie-picture-backend
          ports:
            - containerPort: 5000
