apiVersion: v1
kind: Service
metadata:
  name: movie-picture-backend
  labels:
    app: movie-picture-backend
spec:
  type: LoadBalancer
  selector:
    app: movie-picture-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
